# Generated by Django 5.0.4 on 2024-07-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_myuser_last_online_myuser_rating_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=150, verbose_name='username')),
                ('reciever', models.CharField(max_length=150, verbose_name='username')),
                ('rating', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
