# Generated by Django 5.0.4 on 2024-07-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ratinglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='rating_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество оценивших'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='total_rating',
            field=models.IntegerField(blank=True, default=0, verbose_name='Общий счёт рейтинга'),
        ),
        migrations.AlterField(
            model_name='ratinglog',
            name='reciever',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ratinglog',
            name='sender',
            field=models.CharField(max_length=150),
        ),
    ]
