# Generated by Django 5.0.4 on 2024-07-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_myuser_rating_count_alter_myuser_total_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pupil', models.CharField(max_length=150)),
                ('teacher', models.CharField(max_length=150)),
            ],
        ),
    ]
