# Generated by Django 5.0.4 on 2024-07-24 20:30

import django.core.validators
import lessons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=lessons.models.lessons_file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'doc', 'docx', 'pdf', 'xls', 'md'])]),
        ),
    ]
