# Generated by Django 5.0.4 on 2024-07-24 20:49

import lessons.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateTimeField(validators=[lessons.validators.validate_date_time]),
        ),
    ]
